version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    open-pull-requests-limit: 15
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/functions"
    open-pull-requests-limit: 15
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 15
    schedule:
      interval: "daily"
