name: Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['12', '14']

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2
      with:
        node-version: ${{ matrix.node_version }}

    - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> frontend/.npmrc

    - name: Install dependencies
      run: cd frontend && npm ci

    - name: Build
      run: cd frontend && npm run build

  build-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['10', '12', '14']

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2
      with:
        node-version: ${{ matrix.node_version }}

    - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> functions/.npmrc

    - name: Install dependencies
      run: cd functions && npm ci

    - name: Build
      run: cd functions && npm run build
